# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

add_to_path(){
    export PATH+=:"$1"
}
#add bat program
#https://github.com/sharkdp/bat#using-bat-on-windows
add_to_path '/d/Applications/Unix/bat-v0.18.3-x86_64-pc-windows-gnu/bat-v0.18.3-x86_64-pc-windows-gnu'
add_to_path '/d/Applications/Unix/Git/usr/bin'
add_to_path "$HOME/.config/scripts"

export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --no-ignore-vcs'
export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border'
